import Outfit from "next/font/local";
import "./globals.css";

const outfit= Outfit({
  src: "./fonts/GeistVF.woff",
  variable: "--font-outfit",
  weight: "400 500 600 700 900",
});
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "BLog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${outfit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
